version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: 397324722998.dkr.ecr.ap-south-1.amazonaws.com/web:0.0.1
    ports:
      - "8080:8080"
    environment:
      app_name: docker
    networks:
      - eks-demo-network
networks:
  eks-demo-network: