apiVersion: v1
kind: Pod
metadata:
  name: web1
  labels:
    app: web1
spec:
  containers:
    - name: web-ctr
      image: 397324722998.dkr.ecr.ap-south-1.amazonaws.com/web:0.0.1
      ports:
        - containerPort: 8080
#      resources:
#        limits:
#          memory: 256Mi
#          cpu: 0.5
      env:
        - name: app_name
          value: container1
