apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 10
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
        env: dev
    spec:
      containers:
      - name: hello-pod
        image: deepakarya0155/kubenatiesspringhelloworld:0.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 0.2
        imagePullPolicy: Always
        env:
        - name: app_name
          value: DEV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deploy
  namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-pod
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 10
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: health-pod
        env: dev
    spec:
      containers:
      - name: health-container
        image: deepakarya0155/kubenatieshealthchecker:0.0.2
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: 512Mi
            cpu: 0.2
        imagePullPolicy: Always
        env:
        - name: http.web-app
          value: http://svc-abc:8080/health
---
apiVersion: v1
kind: Service
metadata:
  name: svc-abc
  namespace: ingress-nginx
spec:
  selector:
    app: hello-world
    env: dev
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003  
---
apiVersion: v1
kind: Service
metadata:
  name: health-abc
  namespace: ingress-nginx
spec:
  selector:
    app: health-pod
    env: dev
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30004 