apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
      env: dev
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web2
        env: dev
    spec:
      containers:
      - name: hello-pod
        image: deepakarya0155/kubenatiesspringhelloworld:0.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 0.2
        imagePullPolicy: Always
        env:
        - name: app_name
          value: DEV
---
apiVersion: v1
kind: Service
metadata:
  name: svc-abc
  namespace: dev
spec:
  selector:
    app: web2
    env: dev
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003   