kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    env: dev1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e1-deploy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 100
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-pod
        image: deepakarya0155/kubenatiesspringhelloworld:0.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 0.2
        imagePullPolicy: Always
        env:
        - name: app_name
          value: DEV
        volumeMounts:
        - name: web-volume
          mountPath: /log123
      volumes:
      - name: web-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: dev
spec:
  selector:
    app: healthcheck
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30005

