apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy-prod
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
        env: prod
    spec:
      containers:
      - name: hello-pod
        image: deepakarya0155/kubenatiesspringhelloworld:0.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 0.2
        imagePullPolicy: Always
        env:
        - name: app_name
          value: PROD
---
apiVersion: v1
kind: Service
metadata:
  name: svc-abc-prod
spec:
  selector:
    app: hello-world
    env: prod
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30004   