kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    env: dev1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-config-map
  namespace: dev
  labels:
    env: dev1
data:
  app_name: FFFF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e1-deploy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 10
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-pod
        image: deepakarya0155/kubenatiesspringhelloworld:0.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 0.2
        imagePullPolicy: Always
        env:
        - name: app_name
          valueFrom:
            configMapKeyRef:
              name: dev-config-map
              key: app_name
        volumeMounts:
          - name: volmap
            mountPath: /app
      volumes:
        - name: volmap
          configMap:
            name: test-config

---
apiVersion: v1
kind: Service
metadata:
  name: abc-svc
  namespace: dev
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30006
