apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dev
  name: default
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-2
  labels:
    zone: dev
    version: v1
    app: abc
  namespace: dev
spec:
  containers:
  - name: hello-ctr
    image: deepakarya0155/kubenatiesspringhelloworld:0.0.1
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5
    env:
    - name: app_name
      value: container1
    imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: svc-abc
  namespace: dev
spec:
  selector:
    app: abc
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30012    